### ISSUE TITLE
New DB Request | BigQuery

### ISSUE THREAD

**Issue by cpdough** [rasgointelligence/RasgoQL#14]
Would like to use RasgoQL with BigQuery

**Open questions:**

- will transform templates need changes to support BigQuery SQL syntax?
- may need to support google oauth login since creds are typically tired to a google account

**Comment by griffatrasgo** [comment]
Thanks for the request. Your check is in the mail.

> will transform templates need changes to support BigQuery SQL syntax?
Yes, this will require a corresponding change to the `rasgotransforms` package. Most of our transforms were originally optimized to run on Snowflake. Any transforms that use Snowflake-specific syntax will need to be converted to run in ANSI SQL.

**Comment by griffatrasgo** [comment]
Initial support for BigQuery will be available in release 1.0.0
