### ISSUE TITLE
Trouble with import

### ISSUE THREAD

**Issue by mashhype** [rasgointelligence/RasgoQL#72]
**Describe the bug**
I get this error when I try to pip install rasgoql[snowflake]: no matches found: rasgoql[snowflake]

Prior to running this, I successfully downloaded the snowflake connector...

**To Reproduce**
go to bash and type:  pip install rasgoql[snowflake]  

**Expected Behavior**:
successful import

**Actual Behavior**:
bash returns:  no matches found: rasgoql[snowflake]

**Version Information (please complete the following information):**
 rasgoql==1.1.1
 rasgotransforms==1.1.3

**Additional context**
I'm trying to connect to a trial snowflake account

**Comment by griffatrasgo** [comment]
Hi @mashhype thanks for the question. This is a quirk of pip in some IDEs. You should have more success wrapping `rasgoql[snowflake]` in double quotes.

Can you try running `pip install "rasgoql[snowflake]"` and let us know if this works?

**Comment by Nick-Harvey** [comment]
Try wrapping it in quotes 'rasgoql[snowflake]'

**Comment by mashhype** [comment]
> Hi @mashhype thanks for the question. This is a quirk of pip in some IDEs. You should have more success wrapping `rasgoql[snowflake]` in double quotes.
> 
> Can you try running `pip install "rasgoql[snowflake]"` and let us know if this works?

This worked :)
